#!/bin/sh -x

# create database with name as dish_test
DATABASE_NAME='dish_test'
if psql -lqt | cut -d \| -f 1 | grep -qw $DATABASE_NAME; then
    echo "A database with the name $DBNAME already exists."
    echo "Drop $DATABASE_NAME and create a new one."
    dropdb $DATABASE_NAME
fi
createdb $DATABASE_NAME

# Export the environment variables and set up for the server
export DATABASE_URL='postgresql://localhost:5432/dish_test' 
export ADMIN_TOKEN='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik56RXpNemt6UmtFMVFrTkdSREF5TkRJek1Ea3hSRGhFT1RJNFJFWTJNek5HUWtaRFJUY3dSQSJ9.eyJpc3MiOiJodHRwczovL2Rldi1hdXRoMi5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWU2NDg2NDVjNmRiYzkwZDNkZTJkMDdjIiwiYXVkIjoiRGlzaGVzIiwiaWF0IjoxNTkyNjI3NTk5LCJleHAiOjE1OTI3MTM5OTksImF6cCI6ImVDYzRCdGM2RU9OY1VMYTFzY0VXaUlCMzJ4M1BaeEJkIiwic2NvcGUiOiIiLCJwZXJtaXNzaW9ucyI6WyJkZWxldGU6Y2F0ZWdvcmllcyIsImRlbGV0ZTpkaXNoZXMiLCJkZWxldGU6cmVzdGF1cmFudHMiLCJnZXQ6Y2F0ZWdvcmllcyIsImdldDpkaXNoZXMiLCJnZXQ6cmVzdGF1cmFudHMiLCJwYXRjaDpjYXRlZ29yaWVzIiwicGF0Y2g6ZGlzaGVzIiwicGF0Y2g6cmVzdGF1cmFudHMiLCJwb3N0OmNhdGVnb3JpZXMiLCJwb3N0OmRpc2hlcyIsInBvc3Q6cmVzdGF1cmFudHMiXX0.jSylt8oUhsqvXmwybs1RMQdcSouv8xAMeXsoCUUgdwkzoXzmNefETBeflc4OF7nNQ6ElNH-XeeJHtY8GQBOxEoi-g6xklTRsqrMrIu7EMFwzhRYumUz0w_DK1U3PCbZvRBqgF4H_pUC9Unxlt-Xu_P-6lNQAdWxfSPOE-r0V5XHKNQBKtAUn3JekfBprmVzhnBOYEwAcGokzlIg8pAN-7SAP5-8MLRA9B73DbxAexi5Y16hc1b9lHPOMPb0GoqYeKBSuwFcJF0QsuqgK_bTINRmrS93Bij0aI4YJSJV8Z27j_hGuldqubSY_Uculojqqc5M8NN8vzEgFzniytgmDYQ'
export USER_TOKEN='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik56RXpNemt6UmtFMVFrTkdSREF5TkRJek1Ea3hSRGhFT1RJNFJFWTJNek5HUWtaRFJUY3dSQSJ9.eyJpc3MiOiJodHRwczovL2Rldi1hdXRoMi5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWU5NTVhN2MzNDdlYjAwYzE3MThhM2MzIiwiYXVkIjoiRGlzaGVzIiwiaWF0IjoxNTkyNjI3NjM5LCJleHAiOjE1OTI3MTQwMzksImF6cCI6ImVDYzRCdGM2RU9OY1VMYTFzY0VXaUlCMzJ4M1BaeEJkIiwic2NvcGUiOiIiLCJwZXJtaXNzaW9ucyI6WyJnZXQ6Y2F0ZWdvcmllcyIsImdldDpkaXNoZXMiLCJnZXQ6cmVzdGF1cmFudHMiXX0.amfVf2r47wBN9vx65LSzwgZDDhxxCNN_31vdiiS24q_Ae-PjcPSfY14cs6xE16L-TAWhipPmOsYV4-8Hp05QdcG6aPC8vXWQiuuJAOrHTFj_xpCINnMkeJuuJNeVqvQqKwa83BXam3FEfU9awQPYE9Y5Ws2c0a2MwX8hOENeM_vTUSRjUWpMNMaVvIBwZ_h_NFJYmYpSU7Xyx06C-QIPBdsNx9cfzRDx7LSoSGOzqTisqRX9gIXJHlx1AOk_Xm5qK0QuCeo2QUy9swhrazFGWRCOM0HM_ZZqkkw9re6u6mI6EgzwgZWoH1wipekDw40IsUCo1XlGr0LyxPVkeLsotw' 
python3 -m backend.src.test -v